### ISSUE TITLE
[Rarity] Add check boxes to choose between GE/HA values

### ISSUE THREAD

**Issue by Jin-Jiyunsun** [Zamatica/ItemRarity#2]
Add an option to just use either GE or high alch values as it looks like right now it uses a sum of both

**Comment by Zamatica** [comment]
Currently, we are doing a max between the store price, high alch, and GE prices. That being said, the HA price is a percentage of the store price.

We went ahead and added two checkboxes that work according:
- Both Checked: Uses Max between HA & GE
- One Checked: Uses that price.
- None checked: Uses 0, effectively turns off the highlighting.

**Comment by Zamatica** [comment]
If that sounds good to your suggestion, I'll wait to close the issue.

**Comment by Jin-Jiyunsun** [comment]
that sounds good to me, when can we expect to see it updated on runelite?

**Comment by Zamatica** [comment]
Probably in the next few days. Unfortunately, I have a few big assignments due that I need to focus on.

Thanks again for the suggestion!
